sudo: false
language: python
python:
  - "3.7"

os: linux

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

before_script:
  - psql -c 'create database helios;' -U postgres

script: "python3 -Wall manage.py test"

jobs:
  include:
  - dist: trusty
    addons:
      postgresql: "9.3"
  - dist: trusty
    addons:
      postgresql: "9.4"
  - dist: trusty
    addons:
      postgresql: "9.5"
  - dist: trusty
    addons:
      postgresql: "9.6"
  - dist: xenial
    addons:
      postgresql: "9.4"
  - dist: xenial
    addons:
      postgresql: "9.5"
  - dist: xenial
    addons:
      postgresql: "9.6"
