# Generated by Django 2.2.11 on 2020-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0004_auto_20170528_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='datatype',
            field=models.CharField(default='legacy/Election', max_length=250),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('election', 'Election'), ('referendum', 'Referendum')], default='election', max_length=250),
        ),
        migrations.AlterField(
            model_name='voterfile',
            name='voter_file',
            field=models.FileField(max_length=250, null=True, upload_to='voters/%Y/%m/%d'),
        ),
        migrations.AlterUniqueTogether(
            name='trustee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='trustee',
            constraint=models.UniqueConstraint(fields=('election', 'email'), name='unique_email_by_election'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(voter_login_id=None), fields=('election', 'user'), name='voter_user_in_election'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(user=None), fields=('election', 'voter_login_id'), name='voter_id_in_election'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, alias=None), fields=('election', 'alias'), name='voter_alias_in_election'),
        ),
    ]
